export enum AppStorageMap {
  USER_INFO = "userInfo",
  TOKEN = "token",
  PRIVACY_POLICY_KEY = "privacyPolicyKey"
}

export enum RouterMap {
  // 启动页
  LAUNCH_PAGE = "LaunchPage",
  // 广告页
  LAUNCH_AD_PAGE = "LaunchAdPage",
  // 主页面
  MAIN_PAGE = "MainPage",
  // 隐私协议页
  PRIVACY_POLICY_PAGE = "PrivacyPolicyPage",
  // 首页
  HOME_PAGE = "HomePage",
  // 课程页面
  COURSE_PAGE = "CoursePage",
  // 学习页面
  LEARN_PAGE = "LearnPage",
  // 个人主页
  PROFILE_PAGE = "ProfilePage",
  // 登录页面
  LOGIN_PAGE = "LoginPage",
  // 课程详情页面
  COURSE_DETAIL_PAGE = "CourseDetailPage",
  // 搜索页面
  SEARCH_PAGE = "SearchPage",
  // 消息页面
  MESSAGE_PAGE = "MessagePage",
}